# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: truckmatch-api-service
  namespace: truckmatch
spec:
  selector:
    app: truckmatch-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
